insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 1, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.28);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 2, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.12);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 3, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.42);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 4, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 8.39);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 5, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 5.24);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 6, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 8.61);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 7, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 3.69);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 8, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 11.61);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 9, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.32);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 10, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 11.88);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 11, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.42);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 12, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 8.42);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 13, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 4.86);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 14, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.01);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 15, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 3.18);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 16, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 4.41);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 17, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 2.56);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 18, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.39);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 19, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.5);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 20, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 6.06);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 21, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.43);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 22, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.45);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 23, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 12.3);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 24, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 4.72);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 25, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.56);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 26, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 11.59);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 27, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 8.49);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 28, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.63);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 29, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.7);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 30, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.53);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 31, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 12.33);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 32, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 12.81);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 33, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 9.51);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 34, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.89);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 35, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 12.32);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 36, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.22);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 37, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.58);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 38, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 3.21);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 39, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 8.76);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 40, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.21);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 41, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 2.57);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 42, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.38);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 43, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.59);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 44, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.61);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 45, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 3.38);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 46, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 7.63);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 47, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.87);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 48, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.65);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 49, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 4.4);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 50, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 3.49);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 51, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 9.77);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 52, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.75);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 53, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 1.92);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 54, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 12.1);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 55, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 10.19);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 56, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 11.08);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 57, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 4.66);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Simple', 58, 'Desayuno y cena incluidas', 'Breakfast and dinner included', 8.43);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 1, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 41.36);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 2, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 24.11);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 3, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 23.75);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 4, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 40.72);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 5, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 15.48);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 6, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 24.19);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 7, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 21.7);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 8, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 18.12);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 9, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 12.9);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 10, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 12.42);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 11, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 20.01);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 12, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 13.49);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 13, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 15.41);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 14, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 36.75);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 15, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 29.02);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 16, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 22.25);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 17, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 41.67);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 18, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 38.71);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 19, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 17.83);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 20, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 22.94);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 21, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 40.3);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 22, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 16.67);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 23, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 38.85);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 24, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 19.5);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 25, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 26.92);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 26, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 32.69);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 27, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 35.63);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 28, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 34.08);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 29, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 12.77);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 30, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 31.68);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 31, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 26.14);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 32, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 26.16);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 33, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 16.51);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 34, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 44.34);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 35, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 25.51);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 36, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 36.95);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 37, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 17.2);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 38, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 33.93);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 39, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 16.28);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 40, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 44.66);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 41, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 29.85);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 42, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 37.76);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 43, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 33.06);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 44, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 34.69);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 45, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 26.7);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 46, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 31.37);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 47, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 34.46);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 48, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 27.11);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 49, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 35.8);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 50, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 43.72);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 51, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 22.21);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 52, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 35.61);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 53, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 39.47);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 54, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 12.52);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 55, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 25.91);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 56, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 43.2);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 57, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 37.42);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Gourmet', 58, 'Desayuno de lujo incluido', 'Exotic breakfast Included', 22.79);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 1, 'Todo lo que puedas comer siempre', 'always', 19.89);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 2, 'Todo lo que puedas comer siempre', 'always', 12.29);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 3, 'Todo lo que puedas comer siempre', 'always', 14.75);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 4, 'Todo lo que puedas comer siempre', 'all you can eat', 16.85);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 5, 'Todo lo que puedas comer siempre', 'all you can eat', 14.28);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 6, 'Todo lo que puedas comer siempre', 'always', 18.61);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 7, 'Todo lo que puedas comer siempre', 'all you can eat', 18.54);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 8, 'Todo lo que puedas comer siempre', 'always', 17.67);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 9, 'Todo lo que puedas comer siempre', 'always', 17.14);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 10, 'Todo lo que puedas comer siempre', 'all you can eat', 15.77);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 11, 'Todo lo que puedas comer siempre', 'all you can eat', 15.14);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 12, 'Todo lo que puedas comer siempre', 'always', 19.96);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 13, 'Todo lo que puedas comer siempre', 'always', 16.93);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 14, 'Todo lo que puedas comer siempre', 'all you can eat', 19.27);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 15, 'Todo lo que puedas comer siempre', 'always', 18.77);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 16, 'Todo lo que puedas comer siempre', 'all you can eat', 18.73);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 17, 'Todo lo que puedas comer siempre', 'all you can eat', 17.3);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 18, 'Todo lo que puedas comer siempre', 'always', 13.65);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 19, 'Todo lo que puedas comer siempre', 'all you can eat', 19.1);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 20, 'Todo lo que puedas comer siempre', 'always', 12.75);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 21, 'Todo lo que puedas comer siempre', 'always', 13.39);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 22, 'Todo lo que puedas comer siempre', 'all you can eat', 19.16);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 23, 'Todo lo que puedas comer siempre', 'all you can eat', 14.45);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 24, 'Todo lo que puedas comer siempre', 'always', 19.06);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 25, 'Todo lo que puedas comer siempre', 'all you can eat', 15.25);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 26, 'Todo lo que puedas comer siempre', 'always', 20.03);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 27, 'Todo lo que puedas comer siempre', 'always', 20.26);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 28, 'Todo lo que puedas comer siempre', 'all you can eat', 19.91);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 29, 'Todo lo que puedas comer siempre', 'always', 12.06);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 30, 'Todo lo que puedas comer siempre', 'always', 17.53);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 31, 'Todo lo que puedas comer siempre', 'all you can eat', 12.45);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 32, 'Todo lo que puedas comer siempre', 'always', 12.46);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 33, 'Todo lo que puedas comer siempre', 'always', 12.3);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 34, 'Todo lo que puedas comer siempre', 'all you can eat', 20.16);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 35, 'Todo lo que puedas comer siempre', 'always', 15.07);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 36, 'Todo lo que puedas comer siempre', 'all you can eat', 17.06);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 37, 'Todo lo que puedas comer siempre', 'always', 12.87);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 38, 'Todo lo que puedas comer siempre', 'all you can eat', 12.09);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 39, 'Todo lo que puedas comer siempre', 'all you can eat', 12.36);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 40, 'Todo lo que puedas comer siempre', 'all you can eat', 19.68);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 41, 'Todo lo que puedas comer siempre', 'always', 19.62);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 42, 'Todo lo que puedas comer siempre', 'always', 14.73);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 43, 'Todo lo que puedas comer siempre', 'always', 15.22);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 44, 'Todo lo que puedas comer siempre', 'always', 15.44);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 45, 'Todo lo que puedas comer siempre', 'all you can eat', 14.71);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 46, 'Todo lo que puedas comer siempre', 'all you can eat', 18.39);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 47, 'Todo lo que puedas comer siempre', 'all you can eat', 20.37);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 48, 'Todo lo que puedas comer siempre', 'all you can eat', 14.95);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 49, 'Todo lo que puedas comer siempre', 'all you can eat', 12.24);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 50, 'Todo lo que puedas comer siempre', 'always', 15.77);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 51, 'Todo lo que puedas comer siempre', 'all you can eat', 15.32);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 52, 'Todo lo que puedas comer siempre', 'always', 18.52);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 53, 'Todo lo que puedas comer siempre', 'always', 18.03);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 54, 'Todo lo que puedas comer siempre', 'always', 14.35);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 55, 'Todo lo que puedas comer siempre', 'all you can eat', 16.63);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 56, 'Todo lo que puedas comer siempre', 'always', 14.98);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 57, 'Todo lo que puedas comer siempre', 'always', 14.37);
insert into plancomida (nomplan, idhotel, descrplan, descrplaneng, precioplan) values ('Buffet', 58, 'Todo lo que puedas comer siempre', 'always', 18.14);
