insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 59.25, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 144.13, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 31);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 140.12, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 114);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 108.31, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 36.74, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 68);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 66.17, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 70);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 184.38, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 67);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 53.64, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 109);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 137.22, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 43.55, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 44);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 157.78, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 24);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 51.42, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 8);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 65.1, 'bella habitacion para 2 personas', 'romantic room for 2 people', 78);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 153.85, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 86);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 178.65, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 64.74, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 39);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 147.74, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 10);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 189.55, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 176.15, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 1);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 141.42, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 30);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 100.18, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 78);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 196.62, 'bella habitacion para 2 personas', 'romantic room for 2 people', 27);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 43.82, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 40);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 39.98, 'bella habitacion para 2 personas', 'beautiful room for one person', 101);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 31.78, 'bella habitacion para 2 personas', 'beautiful room for one person', 108);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 33.96, 'bella habitacion para 2 personas', 'beautiful room for one person', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 22.31, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 36);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 64.83, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 194.03, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 79);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 64.17, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 27);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 186.85, 'bella habitacion para 2 personas', 'beautiful room for one person', 62);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 181.09, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 118.97, 'bella habitacion para 2 personas', 'beautiful room for one person', 13);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 89.61, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 62);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 182.39, 'bella habitacion para 2 personas', 'beautiful room for one person', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 102.46, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 75);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 125.36, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 50);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 197.36, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 64.7, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 163.52, 'bella habitacion para 2 personas', 'romantic room for 2 people', 58);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 198.69, 'bella habitacion para 2 personas', 'beautiful room for one person', 34);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 57.45, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 107);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 188.24, 'bella habitacion para 2 personas', 'romantic room for 2 people', 34);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 174.45, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 165.88, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 99);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 139.55, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 191.84, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 95);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 58.97, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 42);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 134.05, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 31);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 195.28, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 93.24, 'bella habitacion para 2 personas', 'beautiful room for one person', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 51.17, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 8);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 79.01, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 104);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 126.72, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 44);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 109.56, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 79);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 29.38, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 90);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 102.68, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 88);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 54.74, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 27.57, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 41.52, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 48);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 165.9, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 78);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 62.93, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 13);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 197.05, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 65.81, 'bella habitacion para 2 personas', 'beautiful room for one person', 60);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 193.73, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 18);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 185.58, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 119.79, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 80);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 148.58, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 99);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 24.47, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 14);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 23.99, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 44);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 154.72, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 43);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 167.68, 'bella habitacion para 2 personas', 'romantic room for 2 people', 14);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 93.29, 'bella habitacion para 2 personas', 'romantic room for 2 people', 76);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 22.14, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 45);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 97.32, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 26);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 101.48, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 1);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 118.95, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 32);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 198.95, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 60);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 173.95, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 99);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 177.22, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 98);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 40.37, 'bella habitacion para 2 personas', 'romantic room for 2 people', 104);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 20.74, 'bella habitacion para 2 personas', 'beautiful room for one person', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 136.04, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 13);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 43.99, 'bella habitacion para 2 personas', 'romantic room for 2 people', 66);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 187.84, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 40);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 116.52, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 1);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 176.44, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 108);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 120.52, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 65);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 42.0, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 31);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 191.7, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 106);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 125.16, 'bella habitacion para 2 personas', 'romantic room for 2 people', 53);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 195.92, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 63.48, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 125.32, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 70);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 115.91, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 54);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 83.67, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 65);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 189.38, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 2);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 94.87, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 112);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 131.1, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 82);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 95.94, 'bella habitacion para 2 personas', 'romantic room for 2 people', 42);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 93.98, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 38);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 47.09, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 26);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 69.66, 'bella habitacion para 2 personas', 'beautiful room for one person', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 136.37, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 114);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 160.14, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 65);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 65.14, 'bella habitacion para 2 personas', 'beautiful room for one person', 84);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 107.64, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 15);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 48.37, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 17);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 123.99, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 77);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 106.16, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 115);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 180.8, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 4);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 118.01, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 17);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 36.77, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 25.04, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 109);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 21.36, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 58);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 186.42, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 183.96, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 82);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 193.98, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 57.86, 'bella habitacion para 2 personas', 'romantic room for 2 people', 25);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 81.26, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 66);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 189.18, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 32);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 166.73, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 107);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 23.38, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 99);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 197.66, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 107);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 195.81, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 76);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 67.68, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 47);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 55.14, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 94);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 135.97, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 35);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 166.72, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 135.72, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 33);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 181.38, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 193.06, 'bella habitacion para 2 personas', 'beautiful room for one person', 55);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 122.38, 'bella habitacion para 2 personas', 'romantic room for 2 people', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 36.2, 'bella habitacion para 2 personas', 'beautiful room for one person', 79);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 133.77, 'bella habitacion para 2 personas', 'beautiful room for one person', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 176.24, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 91.14, 'bella habitacion para 2 personas', 'romantic room for 2 people', 46);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 154.5, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 29);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 183.29, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 99);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 96.51, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 16);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 61.54, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 69);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 125.86, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 18);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 62.43, 'bella habitacion para 2 personas', 'romantic room for 2 people', 93);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 174.67, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 62);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 167.36, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 98);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 26.84, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 109);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 185.79, 'bella habitacion para 2 personas', 'beautiful room for one person', 104);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 174.39, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 61);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 131.42, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 99.59, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 42.37, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 45);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 164.46, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 97);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 165.52, 'bella habitacion para 2 personas', 'beautiful room for one person', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 41.09, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 68);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 74.31, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 66);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 162.72, 'bella habitacion para 2 personas', 'romantic room for 2 people', 92);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 29.68, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 62);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 153.79, 'bella habitacion para 2 personas', 'beautiful room for one person', 116);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 74.93, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 65.21, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 21);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 192.39, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 106);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 185.33, 'bella habitacion para 2 personas', 'romantic room for 2 people', 68);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 21.01, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 16);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 168.36, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 102);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 43.71, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 36);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 150.27, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 49);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 39.7, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 49);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 109.94, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 97);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 56.23, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 11);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 168.64, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 93.31, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 55);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 102.95, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 103);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 152.85, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 109);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 152.72, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 18);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 66.68, 'bella habitacion para 2 personas', 'romantic room for 2 people', 55);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 98.13, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 117.23, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 90);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 25.32, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 101);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 110.68, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 53);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 169.78, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 83);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 124.89, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 102);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 75.04, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 71);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 126.27, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 153.47, 'bella habitacion para 2 personas', 'romantic room for 2 people', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 85.9, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 104);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 185.53, 'bella habitacion para 2 personas', 'beautiful room for one person', 115);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 109.96, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 114);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 173.79, 'bella habitacion para 2 personas', 'romantic room for 2 people', 111);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 162.26, 'bella habitacion para 2 personas', 'romantic room for 2 people', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 114.27, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 119.93, 'bella habitacion para 2 personas', 'romantic room for 2 people', 61);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 198.45, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 68);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 102.88, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 47);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 176.78, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 31);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 39.31, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 95.28, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 96);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 110.61, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 41.53, 'bella habitacion para 2 personas', 'beautiful room for one person', 115);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 100.64, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 77);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 71.22, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 91);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 159.14, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 57);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 76.74, 'bella habitacion para 2 personas', 'romantic room for 2 people', 108);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 132.24, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 98);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 56.35, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 8);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 179.72, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 143.82, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 1);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 179.71, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 21);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 91.12, 'bella habitacion para 2 personas', 'romantic room for 2 people', 19);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 37.71, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 16);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 60.58, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 70);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 178.21, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 88);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 103.0, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 158.87, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 106);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 139.82, 'bella habitacion para 2 personas', 'romantic room for 2 people', 19);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 89.44, 'bella habitacion para 2 personas', 'beautiful room for one person', 38);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 112.6, 'bella habitacion para 2 personas', 'romantic room for 2 people', 103);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 89.02, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 20);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 38.71, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 14);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 94.61, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 3);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 92.07, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 28);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 164.87, 'bella habitacion para 2 personas', 'romantic room for 2 people', 23);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 162.42, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 159.19, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 48);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 99.52, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 28);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 85.09, 'bella habitacion para 2 personas', 'romantic room for 2 people', 61);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 156.18, 'bella habitacion para 2 personas', 'beautiful room for one person', 55);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 191.01, 'bella habitacion para 2 personas', 'beautiful room for one person', 44);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 147.39, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 36);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 48.87, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 72);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 27.08, 'bella habitacion para 2 personas', 'beautiful room for one person', 28);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 128.74, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 62);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 159.87, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 106);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 176.74, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 5);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 144.97, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 63);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 145.61, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 74);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 147.53, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 23);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 67.84, 'bella habitacion para 2 personas', 'beautiful room for one person', 41);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 46.02, 'bella habitacion para 2 personas', 'beautiful room for one person', 112);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 103.46, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 37.48, 'bella habitacion para 2 personas', 'romantic room for 2 people', 100);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 76.55, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 85);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 29.31, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 80);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 189.32, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 110);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 33.88, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 109);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 89.59, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 21);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 127.23, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 47);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 66.32, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 71);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 163.72, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 108);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 88.16, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 46);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 122.06, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 63);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 195.25, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 102);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 181.27, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 50);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 112.7, 'bella habitacion para 2 personas', 'beautiful room for one person', 15);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 89.2, 'bella habitacion para 2 personas', 'romantic room for 2 people', 77);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 160.54, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 81);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 24.92, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 54);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 32.76, 'bella habitacion para 2 personas', 'beautiful room for one person', 30);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 196.93, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 69);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 64.65, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 77);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 166.05, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 98.08, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 66);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 163.41, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 99);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 129.13, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 49);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 129.59, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 21);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 172.05, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 114);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 44.12, 'bella habitacion para 2 personas', 'beautiful room for one person', 71);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 180.07, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 69);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 133.29, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 91);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 107.44, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 94);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 188.16, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 57);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 43.71, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 106);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 167.73, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 104.8, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 45);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 174.73, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 92.47, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 170.8, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 29);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 71.96, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 119.61, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 2);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 172.26, 'bella habitacion para 2 personas', 'beautiful room for one person', 64);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 155.41, 'bella habitacion para 2 personas', 'beautiful room for one person', 106);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 91.54, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 51);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 115.08, 'bella habitacion para 2 personas', 'romantic room for 2 people', 24);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 51.78, 'bella habitacion para 2 personas', 'romantic room for 2 people', 50);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 123.85, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 97);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 175.78, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 75.73, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 95);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 43.09, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 60);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 120.87, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 30);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 102.59, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 96);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 108.3, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 82);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 86.52, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 96);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 116.05, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 35);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 158.37, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 63);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 181.27, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 110);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 21.83, 'bella habitacion para 2 personas', 'romantic room for 2 people', 21);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 105.04, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 75);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 31.19, 'bella habitacion para 2 personas', 'romantic room for 2 people', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 24.33, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 90);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 158.69, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 96.12, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 90);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 112.23, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 145.47, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 30);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 31.22, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 69);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 183.75, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 4);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 163.24, 'bella habitacion para 2 personas', 'romantic room for 2 people', 6);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 180.08, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 98.94, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 11);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 85.37, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 55);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 115.7, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 82);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 93.74, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 102);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 131.61, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 57);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 73.84, 'bella habitacion para 2 personas', 'beautiful room for one person', 68);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 141.28, 'bella habitacion para 2 personas', 'romantic room for 2 people', 92);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 44.03, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 9);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 69.71, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 195.49, 'bella habitacion para 2 personas', 'beautiful room for one person', 1);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 188.87, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 8);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 168.53, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 21);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 165.63, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 35);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 96.0, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 112);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 27.01, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 24);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 23.69, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 14);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 171.64, 'bella habitacion para 2 personas', 'beautiful room for one person', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 24.65, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 59);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 147.44, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 32);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 172.15, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 81);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 194.34, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 20);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 99.17, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 80);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 135.29, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 10);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 71.71, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 50);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 37.32, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 62);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 174.06, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 63);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 115.7, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 65);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 26.15, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 104);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 84.22, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 49);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 142.35, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 119.88, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 112);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 61.63, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 65);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 136.27, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 8);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 72.04, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 4);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 84.71, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 11);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 45.07, 'bella habitacion para 2 personas', 'romantic room for 2 people', 64);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 67.03, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 60);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 85.92, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 53);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 104.22, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 36);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 171.65, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 13);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 187.95, 'bella habitacion para 2 personas', 'beautiful room for one person', 61);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 151.73, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 36.49, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 88);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 37.62, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 43);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 121.03, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 107);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 105.29, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 23);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 90.54, 'bella habitacion para 2 personas', 'beautiful room for one person', 4);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 151.26, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 150.51, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 35);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 170.3, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 46);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 102.56, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 46);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 193.51, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 41.76, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 102);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 170.65, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 133.21, 'bella habitacion para 2 personas', 'beautiful room for one person', 44);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 139.85, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 32);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 33.79, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 160.48, 'bella habitacion para 2 personas', 'romantic room for 2 people', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 190.58, 'bella habitacion para 2 personas', 'romantic room for 2 people', 87);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 36.05, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 73);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 38.26, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 85);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 108.06, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 29);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 20.02, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 90);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 73.84, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 71);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 166.91, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 22);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 167.49, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 68);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 59.71, 'increible suite para 3 o mas personas!', 'romantic room for 2 people', 12);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 100.17, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 1);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 100.14, 'bella habitacion para 2 personas', 'beautiful room for one person', 9);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 107.29, 'bella habitacion para 2 personas', 'beautiful room for one person', 56);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 158.47, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 27);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 179.16, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 64);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 131.15, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 27);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 109.1, 'bella habitacion para 2 personas', 'romantic room for 2 people', 97);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 89.38, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 52);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 118.82, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 67);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 46.83, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 104);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 137.61, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 17);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 29.16, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 11);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 122.34, 'hermosa habitacion para 1 persona', 'beautiful room for one person', 18);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 51.69, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 111);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 116.19, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 4);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 31.6, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 53);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 149.77, 'increible suite para 3 o mas personas!', 'beautiful room for one person', 37);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 62.71, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 72);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 75.43, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 10);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 85.47, 'bella habitacion para 2 personas', 'romantic room for 2 people', 50);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 125.42, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 47);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 175.45, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 59);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 192.76, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 53);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 62.92, 'increible suite para 3 o mas personas!', 'great suite for a big meeting with many people', 89);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (2, 75.78, 'bella habitacion para 2 personas', 'great suite for a big meeting with many people', 67);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (3, 178.97, 'hermosa habitacion para 1 persona', 'great suite for a big meeting with many people', 23);
insert into habitacion (maxperson, prcHabitacion, dethabitacion, dethabitacioneng, idhotel) values (1, 39.19, 'hermosa habitacion para 1 persona', 'romantic room for 2 people', 96);
