
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 72.33, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 0, 14);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 18.94, 'Integer non velit.', 0, 18);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 19.55, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 0, 14);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 80.36, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 0, 17);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 10.48, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 20.88, 'Aliquam quis turpis eget elit sodales scelerisque.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 33.85, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 0, 13);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 22.4, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 0, 21);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 12.67, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 0, 18);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 96.74, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 29.46, 'Nulla mollis molestie lorem. Quisque ut erat.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 91.27, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 0, 23);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 90.25, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 0, 13);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 77.43, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 0, 17);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 79.2, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 0, 18);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 89.55, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 0, 20);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 18.01, 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 0, 18);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 63.77, 'Quisque id justo sit amet sapien dignissim vestibulum.', 0, 19);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 87.7, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 0, 20);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 81.75, 'Phasellus in felis. Donec semper sapien a libero.', 0, 21);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 49.29, 'In eleifend quam a odio. In hac habitasse platea dictumst.', 0, 17);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 23.26, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 0, 23);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 15.28, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 0, 19);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 23.57, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 0, 23);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 57.25, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 0, 22);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 75.7, 'Maecenas tincidunt lacus at velit.', 0, 13);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 69.8, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 0, 18);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 29.91, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 0, 22);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 77.22, 'Nulla nisl. Nunc nisl.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 67.22, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 61.66, 'Nulla ac enim.', 0, 20);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 50.71, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 0, 14);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 50.87, 'Nulla tellus.', 0, 23);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 44.28, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 23.96, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 0, 13);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 90.33, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 0, 21);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 27.3, 'Nulla mollis molestie lorem.', 0, 17);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 20.67, 'Quisque porta volutpat erat.', 0, 15);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 49.41, 'In congue. Etiam justo.', 0, 20);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 87.12, 'Nunc nisl.', 0, 22);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 90.4, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 0, 18);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 42.35, 'Sed accumsan felis.', 0, 17);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (2, 40.9, 'Praesent id massa id nisl venenatis lacinia.', 0, 22);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 99.34, 'Ut at dolor quis odio consequat varius.', 0, 19);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 38.87, 'Nulla nisl. Nunc nisl.', 0, 21);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 39.45, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 0, 17);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 95.46, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 0, 24);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 90.07, 'Pellentesque at nulla. Suspendisse potenti.', 0, 19);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (3, 13.16, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 0, 15);
insert into habitacion (maxPerson, prchabitacion, dethabitacion, estadoreserva, idHotel) values (1, 34.2, 'Morbi a ipsum.', 0, 20);
